name: Binary Builder
on:
  push:
    tags:
      - 'v[0-9]+.*'
  workflow_dispatch:
jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.config.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        config:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: v1.0.0
      - uses: jwlawson/actions-setup-cmake@v1.9
      - run: |
          mkdir build
          cd build
          cmake ..
          make
          mv bin/bam-readcount .
          tar czvf bam-readcount_${{ matrix.config.os }}.tar.gz bam-readcount
        shell: bash
      - uses: actions/upload-artifact@v2
        with:
          name: bin-${{ matrix.config.os }}
          path: build/bam-readcount_*.tar.gz
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file_glob: true
          file: build/bam-readcount_*.tar.gz
